version: '3.9'

services:
  attenzio_database:
    build:
      context: ./database
      dockerfile: database/Dockerfile
    env_file:
      - ./database/.env
    container_name: attenzio_db
    ports:
      - 5432:5432
    networks:
      - bst_network
    volumes:
      - ./database/volume:/var/lib/postgresql/data:rw
  attenzio_backend:
    build:
      context: ./backend
      dockerfile: database/Dockerfile
    env_file:
      - ./backend/.env
    container_name: attenzio_backend
    expose:
      - 8000
    ports:
      - 8000:8000
    networks:
      - bst_network
    depends_on:
      - attenzio_database
    links:
      - attenzio_database:attenzio_database
  attenzio_frontend:
    build:
      context: ./frontend
      dockerfile: database/Dockerfile
    env_file: 
      - ./frontend/.env
    container_name: attenzio_frontend
    restart: always
    expose:
      - "80"  # 3000
    depends_on:
      - attenzio_backend
    ports:
      - "80:3000" # 3000:3000
    networks:
      - bst_network

networks:
  bst_network:
    driver: bridge
